apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kailab-ci

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - resource-quota.yaml
  - network-policy.yaml
  - deployment.yaml
  - image-prepull.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: YOUR_REGISTRY/kailab-runner
    newName: YOUR_REGISTRY/kailab-runner
    newTag: 07b6f52
